// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from supabase/insert_questions_template.sql
// To update: edit the SQL file, then run: npm run sync-sql-template
// Last generated: 2026-01-01T21:48:09.368Z

// SQL template for Gemini follow-up prompt
export const SQL_TEMPLATE = `with mcq_rows as (
select *
from (
values
(
'What is the difference between Option Constraints and Product Rules in Salesforce CPQ, and when would you choose one over the other?',
'Option Constraints and Product Rules both control product selection within a bundle. Option Constraints are best used for simple, binary logic (e.g., "if Product A, then Product B") and are easier to maintain as native fields. Product Rules are used for complex scenarios involving multiple conditions, advanced logic (AND/OR), or acting on fields outside the bundle context.',
'$topic'::public.topic_type,
'$difficulty'::public.difficulty_level,
'$category'::public.question_category,
'$question_type'::public.question_type,
'["Option Constraints for simple binary logic; Product Rules for complex logic/conditions.", "Product Rules for simple logic; Option Constraints for cross-object updates.", "Option Constraints control pricing; Product Rules control visibility.", "They are functionally identical, but Option Constraints are legacy features."]'::jsonb,
0
),
(
'What are Configuration Attributes, and how do they impact Product Options?',
'Configuration Attributes are fields on the bundle configuration page that allow a user to set a value once at the parent level. Using Twin Fields logic, this value cascades down to the specific Product Options, saving the rep from manually setting attributes like Color or Voltage for every component.',
'$topic'::public.topic_type,
'$difficulty'::public.difficulty_level,
'$category'::public.question_category,
'$question_type'::public.question_type,
'["Header-level fields that cascade values to options via Twin Fields.", "Hidden fields used by admins to debug bundles.", "Fields that determine the list price of the bundle parent.", "Attributes that only appear on the generated PDF document."]'::jsonb,
0
),
(
'Explain the "Pricing Waterfall" in Salesforce CPQ. Why is the order important?',
'The Pricing Waterfall is the sequence of price calculations: List Price -> Regular Price -> Customer Price -> Partner Price -> Net Price. The order dictates where custom logic should be injected; for example, knowing if a surcharge applies before or after volume discounts ensures accurate final margins.',
'$topic'::public.topic_type,
'$difficulty'::public.difficulty_level,
'$category'::public.question_category,
'$question_type'::public.question_type,
'["List -> Regular -> Customer -> Partner -> Net", "Net -> Partner -> Customer -> List", "List -> Partner -> Customer -> Regular -> Net", "Customer -> Regular -> List -> Net"]'::jsonb,
0
),
(
'What is "Guided Selling," and what objects are involved in setting it up?',
'Guided Selling is a prompt-based interface that helps reps select products by asking qualifying questions. It involves "Process Inputs" (the questions/logic) and a "Quote Process" record that groups these inputs to filter the product catalog.',
'$topic'::public.topic_type,
'$difficulty'::public.difficulty_level,
'$category'::public.question_category,
'$question_type'::public.question_type,
'["Quote Process and Process Inputs", "Einstein Bot and Chat Settings", "Flow Builder and Screen Elements", "Product Rules and Error Conditions"]'::jsonb,
0
),
(
'How can you ensure a "Setup Fee" is added automatically whenever a specific subscription product is added to the Quote?',
'Create a Product Bundle where the Subscription is the parent and the Setup Fee is a Required, Selected Option. Alternatively, use a "Selection" Product Rule (Add action) to automatically add the Setup Fee line item when the subscription product is detected.',
'$topic'::public.topic_type,
'$difficulty'::public.difficulty_level,
'$category'::public.question_category,
'$question_type'::public.question_type,
'["Bundle with a Required Option or a Selection Product Rule.", "Validation Rule preventing save without the fee.", "Workflow Rule to create a child record.", "Price Rule to update the subscription price."]'::jsonb,
0
)
) as t(question_text, explanation, topic, difficulty, category, question_type, choices, correct_choice_index)
),
inserted_questions as (
insert into public.questions (question_text, answer_text, topic, difficulty, category, question_type)
select question_text, explanation, topic, difficulty, category, question_type
from mcq_rows
returning id, question_text, answer_text
)
insert into public.multiple_choice_questions (question_id, choices, correct_choice_index, explanation)
select iq.id, mr.choices, mr.correct_choice_index, mr.explanation
from inserted_questions iq
join mcq_rows mr on mr.question_text = iq.question_text;`;

export interface PromptOptions {
  topics?: string[];
  categories?: string[];
  difficulties?: string[];
  questionTypes?: string[];
}

export const getFollowUpPrompt = (options?: PromptOptions) => {
  const { topics, categories, difficulties, questionTypes } = options || {};

  let contextInfo = '';

  if (topics && topics.length > 0) {
    contextInfo += `\nAvailable topics: ${topics.join(', ')}`;
  }

  if (categories && categories.length > 0) {
    contextInfo += `\nAvailable categories: ${categories.join(', ')}`;
  }

  if (difficulties && difficulties.length > 0) {
    contextInfo += `\nAvailable difficulty levels: ${difficulties.join(', ')}`;
  }

  if (questionTypes && questionTypes.length > 0) {
    contextInfo += `\nAvailable question types: ${questionTypes.join(', ')}`;
  }

  return `I want to insert the above questions into supabase database. Convert the above questions to the below sql format. don't output anything else${contextInfo}

---

${SQL_TEMPLATE}`;
};
